name: Kubernetes

on:
  workflow_call:

jobs:

  EKS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: git clone https://github.com/Taynan73/Infra_CI_Kubernetes.git

      - name: HashiCorp - Setup Terraform
        # You may pin to the exact commit or the version.
        # uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        uses: hashicorp/setup-terraform@v2.0.3

      - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog init

      - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog apply -auto-approve

      - run: echo "$(terraform -chdir=Infra_CI_Kubernetes/env/Homolog output -raw IP_db)"
        id: URL
      
      - name: Kubectl tool installer
        uses: azure/setup-kubectl@v4
      
      - run: aws sts get-caller-identity

      - run: aws eks update-kubeconfig --region us-east-1 --name homolog2

      - run: kubectl get svc

      - run: kubectl delete secret generic dbhost --ignore-not-found
      - run: kubectl create secret generic dbhost --from-literal=HOST=${{ steps.URL.outputs.stdout }}

      - run: kubectl delete secret generic dbport --ignore-not-found
      - run: kubectl create secret generic dbport --from-literal=DBPORT=${{ secrets.DBPORT }}

      - run: kubectl delete secret generic dbuser --ignore-not-found
      - run: kubectl create secret generic dbuser --from-literal=USER=${{ secrets.DBUSER }}

      - run: kubectl delete secret generic dbpasswod --ignore-not-found
      - run: kubectl create secret generic dbpassword --from-literal=PASSWORD=${{ secrets.DBPASSWORD }}

      - run: kubectl delete secret generic dbname --ignore-not-found
      - run: kubectl create secret generic dbname --from-literal=DBNAME=${{ secrets.DBNAME }}

      - run: kubectl delete secret generic port --ignore-not-found
      - run: kubectl create secret generic port --from-literal=PORT=8000

      - run: kubectl apply -f Infra_CI_Kubernetes/go.yaml
